# Generated by Django 5.1.7 on 2025-05-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetail',
            name='job',
        ),
        migrations.RemoveField(
            model_name='contactdetail',
            name='phone',
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
